---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  # Alpine 3.6 OpenJDK
  - name: java-default-alpine-3.6-openjdk-8-jre
    image: alpine:3.6
  - name: java-default-alpine-3.6-openjdk-8-jdk
    image: alpine:3.6
  # Alpine 3.6 Oracle
  - name: java-default-alpine-3.6-oracle-8-jre
    image: alpine:3.6
  - name: java-default-alpine-3.6-oracle-8-jdk
    image: alpine:3.6
  - name: java-default-alpine-3.6-oracle-9-jre
    image: alpine:3.6
  - name: java-default-alpine-3.6-oracle-9-jdk
    image: alpine:3.6
  - name: java-default-alpine-3.6-oracle-10-jre
    image: alpine:3.6
  - name: java-default-alpine-3.6-oracle-10-jdk
    image: alpine:3.6
  # Alpine 3.7 OpenJDK
  - name: java-default-alpine-3.7-openjdk-8-jre
    image: alpine:3.7
  - name: java-default-alpine-3.7-openjdk-8-jdk
    image: alpine:3.7
  # Alpine 3.7 Oracle
  - name: java-default-alpine-3.7-oracle-8-jre
    image: alpine:3.7
  - name: java-default-alpine-3.7-oracle-8-jdk
    image: alpine:3.7
  - name: java-default-alpine-3.7-oracle-9-jre
    image: alpine:3.7
  - name: java-default-alpine-3.7-oracle-9-jdk
    image: alpine:3.7
  - name: java-default-alpine-3.7-oracle-10-jre
    image: alpine:3.7
  - name: java-default-alpine-3.7-oracle-10-jdk
    image: alpine:3.7
  # CentOS 6 OpenJDK
  - name: java-default-centos-6-default
    image: centos:6
  - name: java-default-centos-6-openjdk-6-jre
    image: centos:6
  - name: java-default-centos-6-openjdk-6-jdk
    image: centos:6
  - name: java-default-centos-6-openjdk-7-jre
    image: centos:6
  - name: java-default-centos-6-openjdk-7-jdk
    image: centos:6
  - name: java-default-centos-6-openjdk-8-jre
    image: centos:6
  - name: java-default-centos-6-openjdk-8-jdk
    image: centos:6
  # CentOS 6 Oracle rpm
  - name: java-default-centos-6-oracle-8-jre-rpm
    image: centos:6
  - name: java-default-centos-6-oracle-8-jdk-rpm
    image: centos:6
  - name: java-default-centos-6-oracle-9-jre-rpm
    image: centos:6
  - name: java-default-centos-6-oracle-9-jdk-rpm
    image: centos:6
  - name: java-default-centos-6-oracle-10-jre-rpm
    image: centos:6
  - name: java-default-centos-6-oracle-10-jdk-rpm
    image: centos:6
  # CentOS 6 Oracle targz
  - name: java-default-centos-6-oracle-8-jre-targz
    image: centos:6
  - name: java-default-centos-6-oracle-8-jdk-targz
    image: centos:6
  - name: java-default-centos-6-oracle-9-jre-targz
    image: centos:6
  - name: java-default-centos-6-oracle-9-jdk-targz
    image: centos:6
  - name: java-default-centos-6-oracle-10-jre-targz
    image: centos:6
  - name: java-default-centos-6-oracle-10-jdk-targz
    image: centos:6
  # CentOS 7 OpenJDK
  - name: java-default-centos-7-default
    image: centos:7
  - name: java-default-centos-7-openjdk-6-jre
    image: centos:7
  - name: java-default-centos-7-openjdk-6-jdk
    image: centos:7
  - name: java-default-centos-7-openjdk-7-jre
    image: centos:7
  - name: java-default-centos-7-openjdk-7-jdk
    image: centos:7
  - name: java-default-centos-7-openjdk-8-jre
    image: centos:7
  - name: java-default-centos-7-openjdk-8-jdk
    image: centos:7
  # CentOS 7 Oracle rpm
  - name: java-default-centos-7-oracle-8-jre-rpm
    image: centos:7
  - name: java-default-centos-7-oracle-8-jdk-rpm
    image: centos:7
  - name: java-default-centos-7-oracle-9-jre-rpm
    image: centos:7
  - name: java-default-centos-7-oracle-9-jdk-rpm
    image: centos:7
  - name: java-default-centos-7-oracle-10-jre-rpm
    image: centos:7
  - name: java-default-centos-7-oracle-10-jdk-rpm
    image: centos:7
  # CentOS 7 Oracle targz
  - name: java-default-centos-7-oracle-8-jre-targz
    image: centos:7
  - name: java-default-centos-7-oracle-8-jdk-targz
    image: centos:7
  - name: java-default-centos-7-oracle-9-jre-targz
    image: centos:7
  - name: java-default-centos-7-oracle-9-jdk-targz
    image: centos:7
  - name: java-default-centos-7-oracle-10-jre-targz
    image: centos:7
  - name: java-default-centos-7-oracle-10-jdk-targz
    image: centos:7
  # Debian Jessie OpenJDK
  - name: java-default-debian-8-default
    image: debian:jessie
  - name: java-default-debian-8-openjdk-7-jre
    image: debian:jessie
  - name: java-default-debian-8-openjdk-7-jdk
    image: debian:jessie
  # Debian Jessie Oracle
  - name: java-default-debian-8-oracle-8-jre
    image: debian:jessie
  - name: java-default-debian-8-oracle-8-jdk
    image: debian:jessie
  - name: java-default-debian-8-oracle-9-jre
    image: debian:jessie
  - name: java-default-debian-8-oracle-9-jdk
    image: debian:jessie
  - name: java-default-debian-8-oracle-10-jre
    image: debian:jessie
  - name: java-default-debian-8-oracle-10-jdk
    image: debian:jessie
  # Debian Buster openjdk
  - name: java-default-debian-buster-openjdk-8-jre
    image: debian:buster
  - name: java-default-debian-buster-openjdk-8-jdk
    image: debian:buster
  - name: java-default-debian-buster-openjdk-9-jre
    image: debian:buster
  - name: java-default-debian-buster-openjdk-9-jdk
    image: debian:buster
  # Debian Buster Oracle
  - name: java-default-debian-buster-oracle-8-jre
    image: debian:buster
  - name: java-default-debian-buster-oracle-8-jdk
    image: debian:buster
  - name: java-default-debian-buster-oracle-9-jre
    image: debian:buster
  - name: java-default-debian-buster-oracle-9-jdk
    image: debian:buster
  - name: java-default-debian-buster-oracle-10-jre
    image: debian:buster
  - name: java-default-debian-buster-oracle-10-jdk
    image: debian:buster

  # Fedora 26 OpenJDK
  - name: java-default-fedora-27-openjdk-8-jre
    image: fedora:27
  - name: java-default-fedora-27-openjdk-8-jdk
    image: fedora:27
  - name: java-default-fedora-27-openjdk-9-jre
    image: fedora:27
  - name: java-default-fedora-27-openjdk-9-jdk
    image: fedora:27
  # Fedora 26 Oracle rpm
  - name: java-default-fedora-27-oracle-8-jre-rpm
    image: fedora:27
  - name: java-default-fedora-27-oracle-8-jdk-rpm
    image: fedora:27
  - name: java-default-fedora-27-oracle-9-jre-rpm
    image: fedora:27
  - name: java-default-fedora-27-oracle-9-jdk-rpm
    image: fedora:27
  - name: java-default-fedora-27-oracle-10-jre-rpm
    image: fedora:27
  - name: java-default-fedora-27-oracle-10-jdk-rpm
    image: fedora:27
  # Fedora 26 Oracle targz
  - name: java-default-fedora-27-oracle-8-jre-targz
    image: fedora:27
  - name: java-default-fedora-27-oracle-8-jdk-targz
    image: fedora:27
  - name: java-default-fedora-27-oracle-9-jre-targz
    image: fedora:27
  - name: java-default-fedora-27-oracle-9-jdk-targz
    image: fedora:27
  - name: java-default-fedora-27-oracle-10-jre-targz
    image: fedora:27
  - name: java-default-fedora-27-oracle-10-jdk-targz
    image: fedora:27
  # Fedora 27 OpenJDK
  - name: java-default-fedora-28-openjdk-8-jre
    image: fedora:28
  - name: java-default-fedora-28-openjdk-8-jdk
    image: fedora:28
  - name: java-default-fedora-28-openjdk-9-jre
    image: fedora:28
  - name: java-default-fedora-28-openjdk-9-jdk
    image: fedora:28
  # Fedora 27 Oracle rpm
  - name: java-default-fedora-28-oracle-8-jre-rpm
    image: fedora:28
  - name: java-default-fedora-28-oracle-8-jdk-rpm
    image: fedora:28
  - name: java-default-fedora-28-oracle-9-jre-rpm
    image: fedora:28
  - name: java-default-fedora-28-oracle-9-jdk-rpm
    image: fedora:28
  - name: java-default-fedora-28-oracle-10-jre-rpm
    image: fedora:28
  - name: java-default-fedora-28-oracle-10-jdk-rpm
    image: fedora:28
  # Fedora 27 Oracle targz
  - name: java-default-fedora-28-oracle-8-jre-targz
    image: fedora:28
  - name: java-default-fedora-28-oracle-8-jdk-targz
    image: fedora:28
  - name: java-default-fedora-28-oracle-9-jre-targz
    image: fedora:28
  - name: java-default-fedora-28-oracle-9-jdk-targz
    image: fedora:28
  - name: java-default-fedora-28-oracle-10-jre-targz
    image: fedora:28
  - name: java-default-fedora-28-oracle-10-jdk-targz
    image: fedora:28
  # Ubuntu Trusty OpenJDK
  # Ubuntu Trusty OpenJDK
  - name: java-default-ubuntu-trusty-openjdk-6-jre
    image: ubuntu:trusty
  - name: java-default-ubuntu-trusty-openjdk-6-jdk
    image: ubuntu:trusty
  - name: java-default-ubuntu-trusty-openjdk-7-jre
    image: ubuntu:trusty
  - name: java-default-ubuntu-trusty-openjdk-7-jdk
    image: ubuntu:trusty
  # Ubuntu Trusty oracle
  - name: java-default-ubuntu-trusty-oracle-8-jre
    image: ubuntu:trusty
  - name: java-default-ubuntu-trusty-oracle-8-jdk
    image: ubuntu:trusty
  - name: java-default-ubuntu-trusty-oracle-9-jre
    image: ubuntu:trusty
  - name: java-default-ubuntu-trusty-oracle-9-jdk
    image: ubuntu:trusty
  - name: java-default-ubuntu-trusty-oracle-10-jre
    image: ubuntu:trusty
  - name: java-default-ubuntu-trusty-oracle-10-jdk
    image: ubuntu:trusty
  # Ubuntu Artful OpenJDK
  - name: java-default-ubuntu-artful-openjdk-8-jre
    image: ubuntu:artful
  - name: java-default-ubuntu-artful-openjdk-8-jdk
    image: ubuntu:artful
  - name: java-default-ubuntu-artful-openjdk-9-jre
    image: ubuntu:artful
  - name: java-default-ubuntu-artful-openjdk-9-jdk
    image: ubuntu:artful
  # Ubuntu Artful oracle
  - name: java-default-ubuntu-artful-oracle-8-jre
    image: ubuntu:artful
  - name: java-default-ubuntu-artful-oracle-8-jdk
    image: ubuntu:artful
  - name: java-default-ubuntu-artful-oracle-9-jre
    image: ubuntu:artful
  - name: java-default-ubuntu-artful-oracle-9-jdk
    image: ubuntu:artful
  - name: java-default-ubuntu-artful-oracle-10-jre
    image: ubuntu:artful
  - name: java-default-ubuntu-artful-oracle-10-jdk
    image: ubuntBionic:artful
  # Ubuntu Bionic OpenJDK
  - name: java-default-ubuntu-bionic-openjdk-8-jre
    image: ubuntu:bionic
  - name: java-default-ubuntu-bionic-openjdk-8-jdk
    image: ubuntu:bionic
  - name: java-default-ubuntu-bionic-openjdk-9-jre
    image: ubuntu:bionic
  - name: java-default-ubuntu-bionic-openjdk-9-jdk
    image: ubuntu:bionic
  # Ubuntu Bionic oracle
  - name: java-default-ubuntu-bionic-oracle-8-jre
    image: ubuntu:bionic
  - name: java-default-ubuntu-bionic-oracle-8-jdk
    image: ubuntu:bionic
  - name: java-default-ubuntu-bionic-oracle-9-jre
    image: ubuntu:bionic
  - name: java-default-ubuntu-bionic-oracle-9-jdk
    image: ubuntu:bionic
  - name: java-default-ubuntu-bionic-oracle-10-jre
    image: ubuntu:bionic
  - name: java-default-ubuntu-bionic-oracle-10-jdk
    image: ubuntu:bionic
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: goss
  lint:
    name: yamllint
